### ISSUE TITLE
AzureVpcPeering link to private DNS zone

### ISSUE THREAD

**Issue by vandjelk** [kyma-project/cloud-manager#1175]
**Description**

Once when AzureVpcPeering between Kyma and remote network is established, resource in the remote (peered) network should be accessible by its DNS names defined in the private DNS zone of the remote subscription.

We should be able to link Kyma network with private DNS zones from remote subscription.

**Reasons**

Kyma workloads should be able to resolve DNS entries from private DNS zones in peered networks.

**Comment by vandjelk** [comment]
This is the final proposal of the APIs:

- Shorter form AzureVNetLink instead of AzureVirtualNetworkLink
- Id suffix is removed to be consistent with other Cloud Manager Azure APIs
- NetworkRef is removed as only Kyma network is supported 

#### SKR API

```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVNetLink
metadata:
  name: kyma-to-example-com
spec:
  remoteVNetLinkName: kyma-to-example-com
  remoteTenant: 1dabcec3-d408-453c-a6a1-ae9f1d15a427
  remotePrivateDnsZone: /subscriptions/9dc4adaf-488c-49ed-bc16-71b678e16fba/resourceGroups/myresourcegroup/providers/Microsoft.Network/privateDnsZones/example.com
```

#### KCP API

```yaml
apiVersion: cloud-control.kyma-project.io/v1beta1
kind: AzureVNetLink
metadata:
  name: a9ba004a-58d0-4e4e-8900-ab9f0e52e9f7
spec:
  scope:
    name: 31e7d039-cd8b-4fe0-8786-9f86fc275717
  remoteRef:
    name: kyma-to-example-com
    namespace: ''
  remoteVNetLinkName: kyma-to-example-com
  remoteTenant: 1dabcec3-d408-453c-a6a1-ae9f1d15a427
  remotePrivateDnsZone: /subscriptions/9dc4adaf-488c-49ed-bc16-71b678e16fba/resourceGroups/myresourcegroup/providers/Microsoft.Network/privateDnsZones/example.com
```

**Comment by vandjelk** [comment]
After short discussing we decided to rename `AzureVNetLink` to `AzureVpcDnsLInk` so the SKR API would now look like:

### SKR

```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVpcDnsLink
metadata:
  name: associate-kyma-to-example-com-dns
spec:
  remoteLinkName: my-vpc-to-private-dns-association
  remoteTenant: 1dabcec3-d408-453c-a6a1-ae9f1d15a427
  remotePrivateDnsZone: /subscriptions/9dc4adaf-488c-49ed-bc16-71b678e16fba/resourceGroups/myresourcegroup/providers/Microsoft.Network/privateDnsZones/example.com
```
