### ISSUE TITLE
AzureVpcPeering spec.remotePeeringName should be unique per remoteVnet

### ISSUE THREAD

**Issue by vandjelk** [kyma-project/cloud-manager#1256]
**Description**

Givent that there are Kyma instances A and B and remote network C

When following AzureVpcPeering is applied to Kyma A
```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVpcPeering
metadata:
  name: mypeering
spec:
  remotePeeringName: mypeering
  remoteVnet: $vnet_C_resource_id
```
Then `mypeering` state is `Ready`

But when the same AzureVpcPeering minifest is applied to Kyma B

Then `mypeering` hangs in `Initiated` state

**Resolution**

AzureVpcPeerings applied to multiple Kyma instances targeting the same remote VNet should have unique `spec.remotePeeringName`

So when the same AzureVpcPeering minifest is applied to Kyma B
Then `mypeering` should be in `Error` state with Error conditions saying that network C already have a peering with the same name.
