### ISSUE TITLE
[Bug] GcpNfsVolume resize problem

### ISSUE THREAD

**Issue by dushanpantic** [kyma-project/cloud-manager#1277]
**Description**

Upon resize, GcpNfsVolume seems to be stuck on `Updating` status state in SKR.
The underlying volume on cloud provider is actually resized.

**Expected result**

- GcpNfsVolume has `Ready` `.status.state` eventually, after the underlying Filestore is resized.
- GcpNfsVolume has `.status.capacityGb` updated to match the actual provisioned value

**Actual result**

- GcpNfsVolume has permanent 'Updating' `.status.state`
- GcpNfsVolume has `.status.capacityGb` value that does not match the provisioned size

**Steps to reproduce**
1. Apply the following manifest:
   ```
   apiVersion: cloud-resources.kyma-project.io/v1beta1
   kind: GcpNfsVolume
   metadata:
     name: update-status-test
     namespace: default 
   spec:
     capacityGb: 1024
     fileShareName: vol1
     tier: BASIC_HDD
   ```
2. Wait for instance to be ready
3. Update the manifest with the following change (`capacityGb` 1024->2048):
   ```
   apiVersion: cloud-resources.kyma-project.io/v1beta1
   kind: GcpNfsVolume
   metadata:
     name: update-status-test
     namespace: default 
   spec:
     capacityGb: 2048
     fileShareName: vol1
     tier: BASIC_HDD
   ```
4. The instance will be stuck in `Updating` status state, and `.status.capacityGb` will not update to reflect the actual provisioned value

**Troubleshooting**
