### ISSUE TITLE
Sample GcpNfsVolume in docs does not work

### ISSUE THREAD

**Issue by tmilos77** [kyma-project/cloud-manager#358]
**Description**

The sample yaml snippet for GcpNfsVolume from the docs https://kyma-project.io/#/cloud-manager/user/resources/04-30-10-gcp-nfs-volume 
```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: GcpNfsVolume
metadata:
  name: my-vol
spec:
  capacityGb: 1024
  location: us-west1
```
does not work and ends up with the Error condition: **googleapi: Error 400: us-west1 is not a valid location for instance creation, it should be a valid GCP zone., badRequest**

**Expected result**

Expected docs samples to work 

**Actual result**

Docs sample does not work

**Steps to reproduce**

In dev b7695d7 GCP apply
```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: GcpNfsVolume
metadata:
  name: my-vol
spec:
  capacityGb: 1024
  location: us-west1
```

**Troubleshooting**
