### ISSUE TITLE
AzureVpcPeering.spec.RemotePeeringName

### ISSUE THREAD

**Issue by vandjelk** [kyma-project/cloud-manager#411]
Created on 2024-08-05 by @vandjelk.

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | AzureVpcPeering.spec.RemotePeeringName |
| Due date | 2024-08-05 |
| Status | Accepted on 2025-08-05 |
| Decision type | Choice |
| Affected decisions | depends on #407(depends on) |

## Context

Recently introduced PeeringName field in AzureVpcPeering API brings confusion if it relates to Kyma or Customer side of the peering. 

## Decision

Following the already adopted prefix Remote for resources that appears in customer subscription, field is renamed to RemotePeeringName.

```yaml
apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVpcPeering
metadata:
  name: azurevpcpeering-sample
spec:
  allowVnetAccess: true
  remotePeeringName: MyPeering
  remoteResourceGroup: MyResourceGroup
  remoteVnet: /subscriptions/afdbc79f-de19-4df4-94cd-6be2739dc0e0/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVnet
```

## Consequences

Remote prefix appears on most of the API fields.
