### ISSUE TITLE
[RedisInstance] add additional data to AuthSecret

### ISSUE THREAD

**Issue by dushanpantic** [kyma-project/cloud-manager#933]
**Description**
Functionality to add additional customer-defined data fields inside the Secret.
Ideally, our well-known fields can be used as template variables in the user defined fields.

Proposal is to have `extraData` field inside the authSecret.

```yaml
...
kind: GcpRedisInstance
...
spec:
  authSecret:
    extraData:
      foo: bar
      hostport: "{{.host}}:{{.port}}
```
In the above example, the created secret would have a `.data.foo` field with value `bar`

**Reasons**

Client requested additional metadata fields that their app needs to function properly.

**Progress**
- [x] Extra data fields are definable
- [x] Well known fields can be used as template variables in definition of extra data
- [x] Relased to prod env

**Attachments**
